"""Manage loading and saving boggle boards."""
import pickle
import csv
from os import path as op
from codecs import open as copen

DICT_PATH = "/usr/share/dict/words"


def load_dictionary(fpath=DICT_PATH):
    """Load the system word list.

    On Linux systems a default word list is included (DICT_PATH).

    Arguments:
        fpath (string) Absolute path to word list file.

    Returns:
        Words (set) Uppercase set of known words `dictionary`.

    """
    with copen(fpath, encoding='utf-8') as f:
        words = f.read().splitlines()
    return(set([x.upper().strip() for x in words]))


def export_words(all_words, fname):
    """Write out to a file all found boggle board words.

    Writes a tab separated value file of found words. Columns are word
    length, word, coordinate chain of grid letters.

    Arguments:
        all_words (dict): Word length indexed set of found words.
        fname (string): Full path of output file.

    Returns:
        output (list): Each found word as a a dictionary

    """
    output = []
    for wlen, words in all_words.items():
        for word, chain in words:
            output.append({'length': wlen, 'word': word, 'path': chain})

    output.sort(key=lambda x: (x['length'], x['word']))
    fhandle = csv.DictWriter(open(fname, mode='w'),
                             fieldnames=["length", "word", "path"])
    fhandle.writeheader()
    fhandle.writerows(output)

    return output


def display_words(words):
    """Print boggle words to screen.

    Arguments:
        words (list): Output word list generated by `export_words`.

    Returns:
        None

    """
    print("{}\t{}\t{}".format("WLEN", "WORD", "PATH"))
    print("="*80)
    for line in words:
        print("{}\t{}\t{}".format(line['length'], line['word'], line['path']))


def _get_board_data_dir():
    """Return the directory for storing board data."""
    x = op.dirname(op.abspath(__file__))
    x = op.abspath(op.join(x, 'data'))
    return x


def export_board_paths(grid, board_data, maxwlen, ow=False):
    """Save all board moves.

    Store computed board paths to limit need to recompute boggle boards.
    Computed boggle boards are stored indexed and pickled:
    number of rows X number of columns - maxwordlength
    The data file is stored in the enclosed boggle/data directory.

    Arguments:
        grid (Grid) Dimensions of boggle board.
        board_data (list) All paths through grid for each `origin`.
        maxwlen (int) Maximum word length
        ow (bool) Force overwrite of stored data (also forces recompute).

    Returns:
        None

    """
    fname = "{}x{}-{}-board.pkl".format(grid.nrow, grid.ncol, maxwlen)
    fname = op.join(_get_board_data_dir(), fname)
    print("Export path: {}".format(fname))

    if op.exists(fname) and ow is False:
        return
    with open(fname, 'wb') as output:
        pickle.dump(board_data, output, pickle.HIGHEST_PROTOCOL)


def import_board_paths(grid, maxwlen):
    """Load `all_path` board moves.

    Loads a previously computed boggle board solution. Pickle stored board_data
    comprises:
        Grid coordinates, digraphs from each grid and coordinate paths.

    Arguments:
        grid (Grid) Boggle board grid of coordinates and dimensions.
        maxwlen (int) Maximum word lengths

    Returns:
        board_data

    """
    fname = "{}x{}-{}-board.pkl".format(grid.nrow, grid.ncol, maxwlen)
    fname = op.join(_get_board_data_dir(), fname)

    if op.exists(fname):
        with open(fname, 'rb') as input:
            board_data = pickle.load(input)
        return (board_data)

    return None
